module Compiler
  class LanguageRecognitionError < StandardError
  end

  class UnsupportedLanguageError < StandardError
  end

  class TokenError < StandardError
  end

  class SyntaxError < StandardError
  end

  class GenerationError < StandardError
  end
end