module Compiler
  class Tokenizer
    PYTHON_TOKENS: [[Symbol,Regexp]]
    JAVA_TOKENS: [[Symbol, Regexp]]
    JS_TOKENS: [[Symbol, Regexp]]
    attr_reader code: String
    attr_reader lang: String?
    def initialize: (String, from_file: bool) -> void
    @code: String
    @lang: String?
    @lang_error: LanguageRecognitionError?
    @token_defs: [[Symbol, Regexp]]

    def identify_lang: -> String

    Token: Class

    class Token
      attr_accessor type: Symbol
      attr_accessor value: String?

      def initialize: (Symbol, String?) -> void
    end

    def tokenize: -> [Token]
    def tokenize_single: -> Token
  end
end