module Compiler
class Tree
attr_accessor root: Node?
  def initialize: (Node?) -> void
  def empty?: -> bool
  def clear: -> void
end

class Node
  def initialize: (Symbol, string) -> void
attr_reader children: []
  attr_reader value: string
  attr_reader type: Symbol
  def size: -> int
  def add: (Symbol, string) -> void
end
end