module COMPILER
class Tree
  @list: [Node]

  attr_accessor list: [Node]
  attr_accessor root: Node?
  attr_accessor node_count: int
def initialize: (Symbol, untyped) -> void
  def add_node: (Node, Symbol, untyped) -> bool
end

class Node
@type: Symbol
@value: untyped
@children: [Node]
def initialize: (Symbol, untyped) -> void

def add_child: (Symbol, untyped) -> Node

end
end