module Compiler

  class LocationRange
    attr_accessor start_loc: Tokenizer::Location | LocationRange
    attr_accessor end_loc: Tokenizer::Location | LocationRange

    def initialize: (Tokenizer::Location | LocationRange, Tokenizer::Location | LocationRange) -> void
  end

  class ASTNode
    attr_reader location: LocationRange | Tokenizer::Location
    def initialize: (LocationRange | Tokenizer::Location) -> void
  end

  class ProgramNode
    attr_accessor nodes: Array[ASTNode]
    def initialize: (Array[ASTNode]) -> void
  end

  class ClassNode < ASTNode
    attr_accessor body: Array[ASTNode]
    def initialize: (Array[ASTNode], LocationRange) -> void
  end

  class FunctionNode < ASTNode
    attr_accessor name: String
    attr_accessor arg_names: Array[ArgNode]
    attr_accessor body: Array[ExpressionNode]
    attr_accessor return_type: String
    attr_accessor modifiers: Array[Symbol]?

    def initialize: (String, Array[ArgNode], Array[ExpressionNode], LocationRange, ?String, ?Array[Symbol]?) -> void
  end

  class ArgNode < ASTNode
    attr_accessor type: String?
    attr_accessor name: String

    def initialize: (String, (Tokenizer::Location | LocationRange), ?String?) -> void
  end

  class BinaryExprNode < ExpressionNode
    attr_accessor left: ExpressionNode
    attr_accessor operator: String
    attr_accessor right: ExpressionNode

    def initialize: (ExpressionNode, String, ExpressionNode, LocationRange) -> void
  end

  class UnaryExprNode < ExpressionNode
    attr_accessor var: ExpressionNode
    attr_accessor operator: String
    attr_accessor is_prefix: bool

    def initialize: (ExpressionNode, String, LocationRange, is_prefix: bool) -> void
  end

  class StatementNode < ASTNode
    def initialize: (LocationRange | Tokenizer::Location) -> void
  end

  class BreakNode < StatementNode
    attr_accessor value: String
    def initialize: (String, Tokenizer::Location) -> void
  end

  class ContinueNode < StatementNode
    attr_accessor value: String
    def initialize: (String, Tokenizer::Location) -> void
  end

  class RetNode < StatementNode
    attr_accessor value: ExpressionNode
    def initialize: (ExpressionNode, LocationRange) -> void
  end

  class ConditionalNode < StatementNode
    attr_accessor condition: ExpressionNode
    attr_accessor body: Array[ExpressionNode]
    def initialize: (ExpressionNode, Array[ExpressionNode], LocationRange) -> void
  end

  class IfNode < ConditionalNode
    attr_accessor else_body: (IfNode | Array[ExpressionNode] | nil)

    def initialize: (ExpressionNode, Array[ExpressionNode], LocationRange, ?(IfNode | Array[ExpressionNode])?) -> void
  end

  class WhileNode < ConditionalNode
    def initialize: (ExpressionNode, Array[ExpressionNode], LocationRange) -> void
  end

  class ForNode < ConditionalNode
    attr_accessor var_init: AssignmentNode | DeclarationNode
    attr_accessor increment: ExpressionNode

    def initialize: (AssignmentNode | DeclarationNode, ExpressionNode, ExpressionNode, Array[ExpressionNode], LocationRange) -> void
  end

  class ExpressionNode < ASTNode
    def initialize: (LocationRange | Tokenizer::Location) -> void
  end

  class ArrDeclNode < ExpressionNode
    attr_accessor values: Array[ExpressionNode]
    def initialize: (Array[ExpressionNode], LocationRange) -> void
  end

  class DeclarationNode < ExpressionNode
    attr_accessor modifiers: Array[String]
    attr_accessor data_type: (String?)
    attr_accessor name: String
    attr_accessor value: ExpressionNode

    def initialize: (Array[String], String, ExpressionNode, LocationRange, ?String?) -> void
  end

  class AssignmentNode < ExpressionNode
    attr_accessor name: String
    attr_accessor value: ExpressionNode

    def initialize: (String, ExpressionNode, LocationRange) -> void
  end

  class NumberNode < ExpressionNode
    attr_accessor value: Integer | Float
    def initialize: (Integer | Float, Tokenizer::Location) -> void
  end

  class IntegerNode < NumberNode
    attr_accessor value: Integer
  end

  class FloatNode < NumberNode
    attr_accessor value: Float
  end

  class ExponentialNode < NumberNode
    attr_accessor value: Float
  end

  class CallNode < ExpressionNode
    attr_accessor name: String
    attr_accessor arg_exprs: Array[ExpressionNode]

    def initialize: (String, Array[ExpressionNode], Tokenizer::Location) -> void
  end

  class VarRefNode < ExpressionNode
    attr_accessor value: String
    def initialize: (String, Tokenizer::Location) -> void
  end

  class StringNode < ExpressionNode
    attr_accessor value: String
    def initialize: (String, Tokenizer::Location) -> void
  end

end