module Compiler

  class ASTNode
    attr_reader location: Tokenizer::Location
    def initialize: (Tokenizer::Location) -> void
  end

  class ProgramNode
    attr_accessor nodes: Array[ASTNode]
    def initialize: (Array[ASTNode]) -> void
  end

  class FunctionNode < ASTNode
    attr_accessor name: String
    attr_accessor arg_names: Array[String]
    attr_accessor body: ExpressionNode

    def initialize: (String, Array[String], ExpressionNode, Tokenizer::Location) -> void
  end

  class ExpressionNode < ASTNode
  end

  class NumberNode < ExpressionNode
    attr_accessor value: Integer | Float
    def initialize: (Integer | Float, Tokenizer::Location) -> void
  end

  class IntegerNode < NumberNode
    attr_accessor value: Integer
  end

  class FloatNode < NumberNode
    attr_accessor value: Float
  end

  class ExponentialNode < NumberNode
    attr_accessor value: Float
  end

  class CallNode < ExpressionNode
    attr_accessor name: String
    attr_accessor arg_exprs: Array[String]

    def initialize: (String, Array[String], Tokenizer::Location) -> void
  end

  class VarRefNode < ExpressionNode
    attr_accessor value: String
    def initialize: (String, Tokenizer::Location) -> void
  end

end