module Compiler

  class Compiler

    attr_reader language: String?
    attr_reader instructions: String?

  def compile: (String, ?from_file: bool, show_instructions: bool) -> String

  def time: -> Float

  private

  def adaptive_round: (float) -> float
end
end
