module Compiler

  class Generator

    attr_reader ast: ProgramNode

    attr_reader instructions: String

    @show_instructions: bool

    @step_list: Array[String]

    @emit_step: Proc

    def initialize: (ProgramNode, bool) -> void

    def generate: (ASTNode | ProgramNode) -> String

    private

    def emit_block: { () -> String } -> String

    def generate_fn: (FunctionNode) -> String

    def generate_expr: (ExpressionNode) -> String

    def generate_stmt: (StatementNode) -> String

    def generate_conditional: (ConditionalNode) -> String

    def generate_if: (IfNode) -> String

    def generate_while: (WhileNode) -> String

    def generate_for: (ForNode) -> String
end

end