module Compiler
  class Parser

    @tokens: [Tokenizer::Token]
    @lang: String

    def initialize: ([Tokenizer::Token], String) -> void

    def parse: -> ProgramNode

    private

    def parse_expr: -> ExpressionNode

    def parse_python: -> Array[ASTNode]

    def parse_java: -> Array[ASTNode]

    def parse_js: -> Array[ASTNode]

    def parse_def: -> FunctionNode

    def parse_number: -> NumberNode
    
    def parse_call: -> CallNode

    def parse_args: -> [String]
    
    def parse_arg_exprs: -> [String]
    
    def parse_var_ref: -> VarRefNode

    def peek?: (Symbol, ?Integer) -> bool

    def peek_type: (?Integer) -> Symbol

    def consume!: (Symbol) -> Tokenizer::Token
  end

end