module Compiler
  class Parser

    @tokens: [Tokenizer::Token]
    @lang: String

    attr_accessor ast: [ASTNode]

    def initialize: ([Tokenizer::Token], String) -> void

    def parse: -> ProgramNode

    private

    def parse_conditional: -> StatementNode

    def parse_while: -> WhileNode

    def parse_break: -> BreakNode

    def parse_continue: -> ContinueNode

    def parse_binary_expr: (?float) -> ExpressionNode

    def parse_if: -> IfNode

    def parse_else: -> (IfNode | Array[ExpressionNode])

    def binding_power: (String) -> [Integer]

    def parse_expr: -> ExpressionNode

    def is_assignment?: -> bool

    def parse_var_set: -> DeclarationNode

    def parse_python: -> Array[ASTNode]

    def parse_java: -> Array[ASTNode]

    def parse_js: -> Array[ASTNode]

    def parse_def: -> FunctionNode

    def parse_number: -> NumberNode
    
    def parse_call: -> CallNode

    def parse_args: -> [String]
    
    def parse_arg_exprs: -> [String]
    
    def parse_var_ref: -> VarRefNode

    def peek?: (Symbol, ?Integer) -> bool

    def peek_type: (?Integer) -> Symbol

    def peek_token: (?Integer) -> Tokenizer::Token

    def consume!: (Symbol) -> Tokenizer::Token

    def loc_range: (Tokenizer::Location | LocationRange, Tokenizer::Location | LocationRange) -> LocationRange
  end

end