

module Compiler


  class Tokenizer
    LANG_TOKENS: Hash[String, [[Symbol, Regexp]]]

    Location: Class
    class Location
      attr_accessor line: Integer
      attr_accessor column: Integer
      attr_accessor length: Integer

      def initialize: (Integer, Integer, Integer) -> void
    end

    Token: Class
    class Token
      attr_accessor type: Symbol
      attr_accessor value: String
      attr_accessor location: Location

      def initialize: (Symbol, String, Location) -> void
    end

    PYTHON_TOKENS: [[Symbol,Regexp]]
    JAVA_TOKENS: [[Symbol, Regexp]]
    JS_TOKENS: [[Symbol, Regexp]]



    @line: Integer

    @position: Integer

    attr_reader code: String
    attr_reader lang: String

    interface _Readable
      def read: () -> String
      def original_filename: () -> String
    end

    def initialize: (String | _Readable,  ?from_file: bool) -> void
    @code: String
    @lang: String
    @token_defs: [[Symbol, Regexp]]
    def tokenize: -> [Token]
    def tokenize_single: -> Token
    def identify_lang: -> String
  end
end